# Generated by Django 3.2.6 on 2021-08-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('client', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('data_init', models.CharField(default='', max_length=70)),
                ('data_end', models.CharField(default='', max_length=70)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tennis_court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(default='', max_length=70)),
                ('type', models.CharField(default='', max_length=70)),
                ('umpire', models.BooleanField(default=False)),
                ('teacher', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
