# Generated by Django 3.2.6 on 2021-08-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tennis_court_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('client', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('date_init', models.CharField(default='', max_length=70)),
                ('date_end', models.CharField(default='', max_length=70)),
                ('referee', models.BooleanField(default=False)),
                ('instructor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tennis_court_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('client', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('date_init', models.CharField(default='', max_length=70)),
                ('date_end', models.CharField(default='', max_length=70)),
                ('referee', models.BooleanField(default=False)),
                ('instructor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tennis_court_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('client', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('date_init', models.CharField(default='', max_length=70)),
                ('date_end', models.CharField(default='', max_length=70)),
                ('referee', models.BooleanField(default=False)),
                ('instructor', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Tennis_court',
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
